{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pexipmedia\/videoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pexipmedia\/videoview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/PexipMedia\/objc(cs)NSView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/PexipMedia\/objc(pl)NSAccessibilityElement","doc:\/\/PexipMedia\/objc(pl)NSAccessibility","doc:\/\/PexipMedia\/objc(pl)NSAnimatablePropertyContainer","doc:\/\/PexipMedia\/objc(pl)NSAppearanceCustomization","doc:\/\/PexipMedia\/objc(pl)NSDraggingDestination","doc:\/\/PexipMedia\/objc(pl)NSStandardKeyBindingResponding","doc:\/\/PexipMedia\/objc(pl)NSTouchBarProvider","doc:\/\/PexipMedia\/objc(pl)NSUserActivityRestoring","doc:\/\/PexipMedia\/objc(pl)NSUserInterfaceItemIdentification","doc:\/\/PexipMedia\/objc(pl)NSCoding","doc:\/\/PexipMedia\/objc(pl)NSObject","doc:\/\/PexipMedia\/s7CVarArgP","doc:\/\/PexipMedia\/s28CustomDebugStringConvertibleP","doc:\/\/PexipMedia\/s23CustomStringConvertibleP","doc:\/\/PexipMedia\/SQ","doc:\/\/PexipMedia\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/isMirrored"]},{"title":"Instance Methods","identifiers":["doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/setFrameSize(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"title":"VideoView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@PexipMedia@objc(cs)VideoView","modules":[{"name":"PexipMedia (macOS)"}],"navigatorTitle":[{"kind":"identifier","text":"VideoView"}]},"hierarchy":{"paths":[["doc:\/\/PexipMedia\/documentation\/PexipMedia"]]},"references":{"doc://PexipMedia/documentation/PexipMedia/VideoView/isMirrored":{"role":"symbol","title":"isMirrored","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMirrored"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/isMirrored","kind":"symbol","type":"topic","url":"\/documentation\/pexipmedia\/videoview\/ismirrored"},"doc://PexipMedia/objc(pl)NSAnimatablePropertyContainer":{"type":"unresolvable","title":"AppKit.NSAnimatablePropertyContainer","identifier":"doc:\/\/PexipMedia\/objc(pl)NSAnimatablePropertyContainer"},"doc://PexipMedia/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/PexipMedia\/objc(pl)NSObject"},"doc://PexipMedia/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/PexipMedia\/SH"},"doc://PexipMedia/objc(pl)NSDraggingDestination":{"type":"unresolvable","title":"AppKit.NSDraggingDestination","identifier":"doc:\/\/PexipMedia\/objc(pl)NSDraggingDestination"},"doc://PexipMedia/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/PexipMedia\/s23CustomStringConvertibleP"},"doc://PexipMedia/documentation/PexipMedia":{"role":"collection","title":"PexipMedia (macOS)","abstract":[{"type":"text","text":"A set of classes and protocols to help with establishing a media connection."}],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia","kind":"symbol","type":"topic","url":"\/documentation\/pexipmedia"},"doc://PexipMedia/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/PexipMedia\/objc(pl)NSCoding"},"doc://PexipMedia/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/PexipMedia\/s7CVarArgP"},"doc://PexipMedia/objc(pl)NSUserActivityRestoring":{"type":"unresolvable","title":"AppKit.NSUserActivityRestoring","identifier":"doc:\/\/PexipMedia\/objc(pl)NSUserActivityRestoring"},"doc://PexipMedia/documentation/PexipMedia/VideoView/setFrameSize(_:)":{"role":"symbol","title":"setFrameSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFrameSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSize","preciseIdentifier":"c:@T@NSSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/setFrameSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFrameSize:"}],"url":"\/documentation\/pexipmedia\/videoview\/setframesize(_:)"},"doc://PexipMedia/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/PexipMedia\/SQ"},"doc://PexipMedia/objc(pl)NSAppearanceCustomization":{"type":"unresolvable","title":"AppKit.NSAppearanceCustomization","identifier":"doc:\/\/PexipMedia\/objc(pl)NSAppearanceCustomization"},"doc://PexipMedia/objc(pl)NSAccessibility":{"type":"unresolvable","title":"AppKit.NSAccessibilityProtocol","identifier":"doc:\/\/PexipMedia\/objc(pl)NSAccessibility"},"doc://PexipMedia/objc(pl)NSStandardKeyBindingResponding":{"type":"unresolvable","title":"AppKit.NSStandardKeyBindingResponding","identifier":"doc:\/\/PexipMedia\/objc(pl)NSStandardKeyBindingResponding"},"doc://PexipMedia/objc(pl)NSAccessibilityElement":{"type":"unresolvable","title":"AppKit.NSAccessibilityElementProtocol","identifier":"doc:\/\/PexipMedia\/objc(pl)NSAccessibilityElement"},"doc://PexipMedia/documentation/PexipMedia/VideoView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/pexipmedia\/videoview\/init(frame:)"},"doc://PexipMedia/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/PexipMedia\/s28CustomDebugStringConvertibleP"},"doc://PexipMedia/objc(cs)NSView":{"type":"unresolvable","title":"NSView","identifier":"doc:\/\/PexipMedia\/objc(cs)NSView"},"doc://PexipMedia/objc(pl)NSTouchBarProvider":{"type":"unresolvable","title":"AppKit.NSTouchBarProvider","identifier":"doc:\/\/PexipMedia\/objc(pl)NSTouchBarProvider"},"doc://PexipMedia/objc(pl)NSUserInterfaceItemIdentification":{"type":"unresolvable","title":"AppKit.NSUserInterfaceItemIdentification","identifier":"doc:\/\/PexipMedia\/objc(pl)NSUserInterfaceItemIdentification"},"doc://PexipMedia/documentation/PexipMedia/VideoView":{"role":"symbol","title":"VideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoView"}],"url":"\/documentation\/pexipmedia\/videoview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"VideoView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VideoView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/init(frame:)","doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/setFrameSize(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSView","preciseIdentifier":"c:objc(cs)NSView"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1setFrameSize(_:)\/title","value":"setFrameSize:"},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1setFrameSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView\/title","value":"VideoView"},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView\/fragments","value":[{"kind":"identifier","text":"VideoView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}