{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pexipmedia\/videoview\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pexipmedia\/videoview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/init(frame:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@PexipMedia@objc(cs)VideoView(im)initWithFrame:","modules":[{"name":"PexipMedia (iOS)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"hierarchy":{"paths":[["doc:\/\/PexipMedia\/documentation\/PexipMedia","doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView"]]},"references":{"doc://PexipMedia/documentation/PexipMedia":{"role":"collection","title":"PexipMedia (iOS)","abstract":[{"type":"text","text":"A set of classes and protocols to help with establishing a media connection."}],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia","kind":"symbol","type":"topic","url":"\/documentation\/pexipmedia"},"doc://PexipMedia/documentation/PexipMedia/VideoView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/pexipmedia\/videoview\/init(frame:)"},"doc://PexipMedia/documentation/PexipMedia/VideoView":{"role":"symbol","title":"VideoView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"abstract":[],"identifier":"doc:\/\/PexipMedia\/documentation\/PexipMedia\/VideoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoView"}],"url":"\/documentation\/pexipmedia\/videoview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView\/title","value":"VideoView"},{"op":"replace","path":"\/references\/doc:~1~1PexipMedia~1documentation~1PexipMedia~1VideoView\/fragments","value":[{"kind":"identifier","text":"VideoView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}