name: 'Bug report'
description: 'Create a bug report to help us improve'
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'To reproduce'
      description: 'Steps that one must take to reproduce the bug.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Version'
      description: 'What library version are you using?'
      placeholder: '0.7.0'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 'Platform'
      options:
      - label: iOS
        required: false
      - label: iPadOS
        required: false
      - label: macOS
        required: false
  - type: textarea
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
