name: 'Feature request'
description: 'Suggest an idea for this project'
labels: ['feature']
body:
  - type: textarea
    attributes:
      label: 'Is your feature request related to a problem? Please describe.'
      description: 'A clear and concise description of what the problem is.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Describe the solution you would like'
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Describe alternatives you have considered'
      description: 'A clear and concise description of any alternative solutions or features you have considered.'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 'Platform'
      options:
      - label: iOS
        required: false
      - label: iPadOS
        required: false
      - label: macOS
        required: false
  - type: textarea
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
