# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'PexipConference', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
  pod 'PexipInfinityClient', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
  pod 'PexipMedia', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
  pod 'PexipRTC', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
  pod 'PexipUtils', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
  pod 'WebRTC', :git => 'https://github.com/pexip/pexip-swift-sdk', :commit => 'a49fd9c6ab6d8ecae0552268c85068f1371568be'
end
