# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'PexipConference', :podspec => '../../PexipConference.podspec'
  pod 'PexipInfinityClient', :podspec => '../../PexipInfinityClient.podspec'
  pod 'PexipMedia', :podspec => '../../PexipMedia.podspec'
  pod 'PexipRTC', :podspec => '../../PexipRTC.podspec'
  pod 'PexipUtils', :podspec => '../../PexipUtils.podspec'
  pod 'WebRTC', :podspec => '../../WebRTC.podspec'
end
