platform :ios, '13.0'
inhibit_all_warnings!

target 'VideoFiltersExample' do
  use_frameworks!
  pod 'PexipCore', :path => '../../'
  pod 'PexipInfinityClient', :path => '../../'
  pod 'PexipMedia', :path => '../../'
  pod 'PexipRTC', :path => '../../'
  pod 'PexipScreenCapture', :path => '../../'
  pod 'PexipVideoFilters', :path => '../../'
  pod 'GoogleMLKit/SegmentationSelfie', '3.2.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end

    target.build_configurations.each do |config|
      if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end

      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
