name: Deploy to CocoaPods trunk

on: 
  workflow_dispatch:
  release:
    types: [published]
      
jobs:
  build:
    runs-on: macos-13    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod repo remove trunk
          pod setup
          pod trunk push PexipCore.podspec --allow-warnings
          pod trunk push PexipScreenCapture.podspec --allow-warnings
          pod trunk push PexipVideoFilters.podspec --allow-warnings
          pod trunk push PexipInfinityClient.podspec --allow-warnings
          pod trunk push PexipMedia.podspec --allow-warnings
          pod trunk push PexipRTC.podspec --allow-warnings
