name: Deploy to CocoaPods trunk

on: 
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    runs-on: macos-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy to CocoaPods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push PexipCore.podspec
        pod trunk push PexipScreenCapture.podspec
        pod trunk push PexipVideoFilters.podspec
        pod trunk push PexipInfinityClient.podspec
        pod trunk push PexipMedia.podspec
        pod trunk push PexipRTC.podspec
