name: Run Danger PR validations

on:
  pull_request:

jobs:
  danger:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache RubyGems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-
    
    - name: Cache Mint packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    
    - name: Install Mint
      run: |
        brew update
        brew upgrade mint || brew install mint || true
        brew link mint
        mint bootstrap
    
    - name: Danger
      uses: MeilCli/danger-action@v5.6.5
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}