name: Check license headers

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check_license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v46

      - name: Check license headers
        run: |
          ./Scripts/license_headers.sh check "${{ steps.files.outputs.all_changed_files }}"
