name: Lint

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.50.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          swiftlint --config .swiftlint-global.yml --strict --reporter github-actions-logging
