name: Run Snyk to check for vulnerabilities

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  snyk:
    runs-on: ubuntu-latest
    container:
      image: docker://snyk/snyk:swift

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          FORCE_COLOR: 2
          SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
          SNYK_INTEGRATION_VERSION: swift
        run: |
          snyk test --strict-out-of-sync=true --severity-threshold=high     
