name: Run Snyk monitor

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  snyk:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Install coreutils for macOS
        run: brew install coreutils

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk monitor
        run: |
          snyk monitor --file=./Examples/VideoFilters/Podfile --strict-out-of-sync=true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
