name: Build and test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-package:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - { destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0' }
          - { destination: 'platform=macOS,arch=x86_64' }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and test
        run: |
          set -o pipefail && xcodebuild \
            -scheme 'Pexip-Package' \
            -destination '${{ matrix.config.destination }}' \
            clean build test | xcpretty

  build-conference-example:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - { scheme: 'Example (iOS)', destination: 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0' }
          - { scheme: 'Example (macOS)', destination: 'platform=macOS,arch=x86_64' }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          set -o pipefail && xcodebuild \
            -project Examples/Conference/Example.xcodeproj \
            -scheme '${{ matrix.config.scheme }}' \
            -destination '${{ matrix.config.destination }}' \
            clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGN_ENTITLEMENTS="" | xcpretty

  build-video-filters-example:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup CocoaPods cache
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods- 
      
      - name: Install CocoaPods
        run: pod install --project-directory=Examples/VideoFilters 
      
      - name: Build
        run: |
          set -o pipefail && arch -x86_64 xcodebuild \
            -workspace Examples/VideoFilters/VideoFiltersExample.xcworkspace \
            -scheme 'VideoFiltersExample' \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0' \
            clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" | xcpretty
